# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63bdc641881cfdc585480b8ec974e3270438754f943bed8cb40bc544827240e0ea3c304b7ddf494962966f0a6ae4583d4dfa5de7ff4db7265b27a2ef4688ef5f

test:
  secret_key_base: f8ae71287664866b22c457b8f48d4dc72bfa3e575a847224f9743cad9882f3457c13b9291f67a443a4a818579cf23aa9ca2da36f7416a08887441eb416d7caed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
